### PR TITLE
fix: Remove hard-coded default read/write concern

### PR DESCRIPTION
**Pull request by alfrunes**

### CODE REVIEW

**Comment by tranchitella** [comment]
@alfrunes why?

**Comment by alfrunes** [comment]
> @alfrunes why?

The linearizable read concern in combination with the latest mongo driver version makes the migration fail in an empty replica set.

**Comment by kjaskiewiczz** [comment]
the pipeline is completely red because of `store/mongo/datastore_mongo.go:31: imported and not used: "go.mongodb.org/mongo-driver/mongo/writeconcern"`, but that's easy to fix;
my question would be - do we need to setup read/write concerns in the code?
we do such things here and there, but we can also do it in the connection string (which is configurable), right?

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline --fast

**Review by kjaskiewiczz — APPROVED** [review]
looks like the right thing to do; thanks!

**Review by tranchitella — APPROVED** [review]

**Pull request merged**
