### PR TITLE
Revert "chore: moved docker image away from root"

### PR DESCRIPTION
**Pull request by mzedel**
This reverts commit fccb82d5196e0cfd2012ac76c0c885989192ef09.

### CODE REVIEW

**Comment by oleorhagen** [comment]
Why?

**Comment by mzedel** [comment]
> @mender-test-bot, Let me know if you want to start the integration pipeline by mentioning me and the command "start pipeline".
> 
> my commands and options

🧱

**Comment by mzedel** [comment]
> Why?

this: https://github.com/mendersoftware/create-artifact-worker/blob/master/Dockerfile#L10 and thus: https://gitlab.com/Northern.tech/Mender/mender-qa/-/jobs/2493094202#L342

**Review by oleorhagen — APPROVED** [review]

**Comment by mzedel** [comment]
https://github.com/mendersoftware/create-artifact-worker/pull/98 should also help...

**Comment by mzedel** [comment]
> > > @mender-test-bot, Let me know if you want to start the integration pipeline by mentioning me and the command "start pipeline".
> > > my commands and options
> > 
> > 
> > 🧱
> 
> 🧱🧱

🧱🧱🧱

**Review by tranchitella — CHANGES_REQUESTED** [review]
What about keeping the server running as non-root, and the worker running as root?

**Comment by mzedel** [comment]
> What about keeping the server running as non-root, and the worker running as root?

with the adjustments from mendersoftware/create-artifact-worker#98 this might not be required at all... 🤞 I'll keep an eye out for related failures for a bit and close this down if none appear...

**Pull request closed without merging**
