### PR TITLE
fix: Job String Processor, Job Processor and support for encoding of variables.

### PR DESCRIPTION
**Pull request by merlin-northern**

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline sugar please

**Review by alfrunes — APPROVED** [review]
LGTM. Should we also update the affected workflows adding the correct encoding to query parameters?

**Comment by merlin-northern** [comment]
> LGTM. Should we also update the affected workflows adding the correct encoding to query parameters?

part of the beauty of one of the previous versions was: by default we encode in the URIs :> so we would not have to do it. I was about to update only in one place in enterprise, since in here there are only ids, scopes and statuses -- all of which will never work with non-URI permitted characters. But I will do it, for clarity, and for documentation :)

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline sugar pretty please honey

**Review by alfrunes — APPROVED** [review]

**Comment by merlin-northern** [comment]
not running the pipeline again, there were only squashes and commit msgs fixes.

**Pull request merged**
