### PR TITLE
fix: Job String Processor, Job Processor and support for encoding of …

### PR DESCRIPTION
**Pull request by merlin-northern**
…variables.

* refactors code around processors
* allows to specify ${encoding=url;workflow.input.identifier}
* sets explicit encoding to url for all input values passed in the URI
* the extension of regular expressions by Alf see workflows/pull/235, workflows/pull/234 with further fixes

Changelog: Support for flags insize the ${workflow.input.identifier} via ${encoding=url;workflow.input.identifier} Changelog: All workflows use encoding=url in the input variables passed in the URIs. Ticket: MEN-5819
Signed-off-by: Peter Grzybowski <peter@northern.tech>
(cherry picked from commit 3787ecbb7f97b4fc74fe723a1ad654718d17de48)

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline

**Comment by merlin-northern** [comment]
we are missing some cherry picks: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/657756990 failed

**Comment by kacf** [comment]
It's https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/657756791 we should be looking at. The other job is because 2.2.x is also used in 3.2.x, but that branch is EOL, so we are not cherry-picking there anymore. It looks like the pipeline I mentioned has only spurious failures, right? The `test_bogus_proto_message` test?

**Review by kacf — APPROVED** [review]

**Comment by merlin-northern** [comment]
> It's https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/657756791 we should be looking at. The other job is because 2.2.x is also used in 3.2.x, but that branch is EOL, so we are not cherry-picking there anymore. It looks like the pipeline I mentioned has only spurious failures, right? The `test_bogus_proto_message` test?

@tranchitella this also concerns your PR, seems we worried needlessly. or I worried :)

**Pull request merged**
